# Generated by Django 3.2.6 on 2021-10-25 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت')),
                ('time1', models.TimeField(null=True, verbose_name='شروع مرخصی')),
                ('time2', models.TimeField(null=True, verbose_name='پایان مرخصی')),
                ('dateexit', django_jalali.db.models.jDateField(verbose_name='تاریخ ورود')),
                ('type', models.CharField(choices=[('ساعتی', 'ساعتی'), ('روزانه', 'روزانه')], default='h', max_length=20, verbose_name='نوع مرخصی')),
                ('accept', models.CharField(choices=[('در دست بررسی', 'در دست بررسی'), ('تایید سرپرست', 'تایید سرپرست'), ('تایید ناظر', 'تایید ناظر'), ('تایید نشده', 'تایید نشده')], default='در دست بررسی', max_length=30, verbose_name='وضیعت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام جایگزین')),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'مرحضی',
                'verbose_name_plural': 'مرحضی',
            },
        ),
        migrations.CreateModel(
            name='Repmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 25, 14, 42, 42), verbose_name='تاریخ ثبت')),
                ('subj', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('name', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.devicemodel', verbose_name='نام قطعه')),
                ('station', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.stationmodel', verbose_name='نام ایستگاه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': ' سیستم قطعات معیوب',
                'verbose_name_plural': 'سیستم قطعات معیوب',
            },
        ),
    ]
