# Generated by Django 3.2.6 on 2021-10-25 11:18

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repmodel',
            name='dev_code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='کد اموال'),
        ),
        migrations.AddField(
            model_name='repmodel',
            name='dev_code1',
            field=models.CharField(max_length=50, null=True, verbose_name='کد انبار'),
        ),
        migrations.AlterField(
            model_name='repmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 25, 14, 48, 51), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='repmodel',
            name='subj',
            field=models.CharField(choices=[('قطعه تحویل مهندسی می باشد', 'قطعه تحویل مهندسی می باشد'), ('قطعه در انبار می باشد', 'قطعه در انبار می باشد'), ('در حال تست', 'در حال تست'), ('نصب شده', 'نصب شده')], max_length=500, verbose_name='توضیحات'),
        ),
    ]
