# Generated by Django 3.2.6 on 2021-10-09 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 10, 0, 58, 59), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='repmodel',
            name='name',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.devicemodel', verbose_name='نام قطعه'),
        ),
    ]
