# Generated by Django 3.2.6 on 2021-10-01 06:47

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_repmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 1, 10, 17, 53), null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
