# Generated by Django 3.2.6 on 2021-10-02 05:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_repmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default='1400-07-10 08:58:53', null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
