# Generated by Django 3.2.6 on 2021-09-30 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='نمایش')),
                ('position', models.IntegerField(verbose_name='موقیعت')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reportmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('report', models.TextField(verbose_name='گزارش')),
                ('date', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 30, 14, 5, 44, 906364), verbose_name='تاریخ ثبت')),
                ('shift', models.CharField(choices=[('شیفت A', 'شیفت A'), ('شیفت B', 'شیفت B'), ('شیفت C', 'شیفت C')], max_length=50, null=True, verbose_name='شیفت')),
                ('acepet', models.CharField(choices=[('تایید نشده', 'تایید نشده'), ('تایید سر شیفت', 'تایید سر شیفت'), ('تایید نهایی', 'تایید نهایی')], default='تایید نشده', max_length=30, verbose_name='وضیعت')),
                ('slug', models.SlugField(max_length=200, unique_for_date='date', verbose_name='آدرس گزارش')),
                ('categ', models.ManyToManyField(related_name='info', to='report.Informationmodel', verbose_name='دسته بندیُ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش',
            },
        ),
    ]
