# Generated by Django 3.2.6 on 2021-09-30 11:36

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 30, 15, 6, 30, 612505), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='آدرس گزارش'),
        ),
    ]
