# Generated by Django 3.2.6 on 2021-09-30 15:50

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210930_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 30, 19, 20, 59, 91436), verbose_name='تاریخ ثبت'),
        ),
    ]
