# Generated by Django 3.2.6 on 2021-10-01 06:40

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 1, 10, 10, 58, 843367), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس گزارش'),
        ),
    ]
