# Generated by Django 3.2.6 on 2021-10-02 05:28

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, verbose_name='تاریخ ثبت'),
        ),
    ]
