# Generated by Django 3.2.6 on 2021-10-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_reportmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report',
            field=models.CharField(max_length=550, verbose_name='گزارش'),
        ),
    ]
