# Generated by Django 3.2.6 on 2021-10-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_reportmodel_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='numbercmms',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره دستور کار'),
        ),
    ]
