# Generated by Django 3.2.6 on 2021-10-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_reportmodel_numbercmms'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50, verbose_name='نام مکان')),
                ('mastername', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.stationmodel', verbose_name='نام')),
            ],
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='subject',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='report.stationmodel', verbose_name='مکان'),
        ),
    ]
