# Generated by Django 3.2.6 on 2021-10-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20211007_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='mastername',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='report.stationmodel', verbose_name='نام'),
        ),
    ]
