# Generated by Django 3.2.6 on 2021-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_alter_stationmodel_mastername'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='position',
            field=models.IntegerField(null=True, verbose_name='موقیعت'),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='titel',
            field=models.CharField(default=2, max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
