# Generated by Django 3.2.6 on 2021-10-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20211007_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='slug',
            field=models.SlugField(default=2, unique=True, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='نمایش '),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='position',
            field=models.IntegerField(default=None, verbose_name='موقیعت'),
        ),
    ]
