# Generated by Django 3.2.6 on 2021-10-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20211007_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=75, verbose_name='نام تجهیز')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش ')),
                ('position', models.IntegerField(default=None, verbose_name='موقیعت')),
            ],
            options={
                'verbose_name': 'نام تجهیز',
                'verbose_name_plural': 'نام تجهیز',
            },
        ),
        migrations.AlterModelOptions(
            name='stationmodel',
            options={'verbose_name': 'نام ایستگاه و مکان های مترو', 'verbose_name_plural': 'نام ایستگاه و مکان های مترو'},
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.devicemodel', verbose_name='نام تجهیز'),
        ),
    ]
